//Music player default state type
export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
export const SET_TOGGLE_RANDOM = 'SET_TOGGLE_RANDOM';
export const SET_TOGGLE_REPEAT = 'SET_TOGGLE_REPEAT';
export const SET_TOGGLE_PLAYING = 'SET_TOGGLE_PLAYING';
export const SET_ACTIVE_PLAYLIST_ARRAY = 'SET_ACTIVE_PLAYLIST_ARRAY';
export const SET_RECENT_SEEK_TIME = 'SET_RECENT_SEEK_TIME';
export const SET_SPECTRUM_TYPE = 'SET_SPECTRUM_TYPE';
export const SET_FAVOURITE_MIX_ITEM = 'SET_FAVOURITE_MIX_ITEM';
export const SET_VOLUME = 'SET_VOLUME';

//Main Application theme state type
export const SET_MAIN_APP_DARKMODE = 'SET_MAIN_APP_DARKMODE';
export const SET_MUSIC_APP_DARKMODE = 'SET_MUSIC_APP_DARKMODE';
export const SET_MIX_ITEM_DURATION = 'SET_MIX_ITEM_DURATION';

//User Profile
export const GET_USER_PROFILE = 'GET_USER_PROFILE';

//Admin Action state type
export const SET_ENABLE_GLOBAL_AUDIO_VISUALIZER = 'SET_ENABLE_GLOBAL_AUDIO_VISUALIZER';
export const SET_ENABLE_GLOBAL_ASTRONOMY_PICTURE = 'SET_ENABLE_GLOBAL_ASTRONOMY_PICTURE';
export const SET_ENABLE_GLOBAL_SHAZAM_SEARCH = 'SET_ENABLE_GLOBAL_SHAZAM_SEARCH';
export const SET_ENABLE_GLOBAL_DOWNLOAD_OPTION = 'SET_ENABLE_GLOBAL_DOWNLOAD_OPTION';
export const SET_ENABLE_GLOBAL_CALM_ANXIETY = 'SET_ENABLE_GLOBAL_CALM_ANXIETY';
export const SET_ENABLE_GLOBAL_ALLOW_USERS_SEE_OTHERS_ONLINE_ACTIVITY = 'SET_ENABLE_GLOBAL_ALLOW_USERS_SEE_OTHERS_ONLINE_ACTIVITY';

//User default state type
export const SET_SHOW_MY_ONLINE_STATUS = 'SET_SHOW_MY_ONLINE_STATUS';
export const SET_SHOW_OTHERS_COMMENTS = 'SET_SHOW_OTHERS_COMMENTS';
export const SET_ALLOW_RANDOM_QUIZ = 'SET_ALLOW_RANDOM_QUIZ';
export const SET_ARTIFICIAL_WEATHER = 'SET_ARTIFICIAL_WEATHER';

//some basic global state type
export const SET_ASTRONOMY_PICTURE = 'SET_ASTRONOMY_PICTURE';
export const SET_GLOBAL_LANGUAGE = 'SET_GLOBAL_LANGUAGE';