//Music player default state type
export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
export const SET_TOGGLE_RANDOM = 'SET_TOGGLE_RANDOM';
export const SET_TOGGLE_REPEAT = 'SET_TOGGLE_REPEAT';
export const SET_TOGGLE_PLAYING = 'SET_TOGGLE_PLAYING';
export const SET_ACTIVE_PLAYLIST_ARRAY = 'SET_ACTIVE_PLAYLIST_ARRAY';
export const SET_RECENT_SEEK_TIME = 'SET_RECENT_SEEK_TIME';
export const SET_FAVOURITE_MIX_ITEM = 'SET_FAVOURITE_MIX_ITEM';
export const SET_VOLUME = 'SET_VOLUME';
export const SET_MIX_ITEM_DURATION = 'SET_MIX_ITEM_DURATION';

//Main Application theme state type
export const SET_MAIN_APP_DARKMODE = 'SET_MAIN_APP_DARKMODE';
export const SET_MUSIC_APP_DARKMODE = 'SET_MUSIC_APP_DARKMODE';
export const SET_SPECTRUM_TYPE = 'SET_SPECTRUM_TYPE';

//Admin Action state type
export const SET_ENABLE_GLOBAL_AUDIO_VISUALIZER = 'SET_ENABLE_GLOBAL_AUDIO_VISUALIZER';
export const SET_ENABLE_GLOBAL_ASTRONOMY_PICTURE = 'SET_ENABLE_GLOBAL_ASTRONOMY_PICTURE';
export const SET_ENABLE_GLOBAL_SHAZAM_SEARCH = 'SET_ENABLE_GLOBAL_SHAZAM_SEARCH';
export const SET_ENABLE_GLOBAL_DOWNLOAD_OPTION = 'SET_ENABLE_GLOBAL_DOWNLOAD_OPTION';
export const SET_ENABLE_GLOBAL_CALM_ANXIETY = 'SET_ENABLE_GLOBAL_CALM_ANXIETY';
export const SET_ENABLE_GLOBAL_ALLOW_USERS_SEE_OTHERS_ONLINE_ACTIVITY = 'SET_ENABLE_GLOBAL_ALLOW_USERS_SEE_OTHERS_ONLINE_ACTIVITY';
//Application stats states
export const SET_CUMMULATIVE_MINUTES_LISTENED = 'SET_CUMMULATIVE_MINUTES_LISTENED';
export const SET_COMMULATIVE_PLAYS_COUNT = 'SET_COMMULATIVE_PLAYS_COUNT';
export const SET_CUMMULATIVE_COMMENTS = 'SET_CUMMULATIVE_COMMENTS';
export const SET_TOTAL_USERS_COUNT = 'SET_TOTAL_USERS_COUNT';
export const SET_TOTAL_SHAZAM_COUNT = 'SET_TOTAL_SHAZAM_COUNT';
export const SET_HIGEST_FAVOURITES = 'SET_HIGEST_FAVOURITES';
export const SET_CUMMULATIVE_DOWNLOADS = 'SET_CUMMULATIVE_DOWNLOADS';
export const SET_CUMMULATIVE_QUIZ_ATTEMPTS = 'SET_CUMMULATIVE_QUIZ_ATTEMPTS';

//User Profile state
export const SET_USER_FIRSTNAME = 'SET_USER_FIRSTNAME'
export const SET_USER_LASTNAME  = 'SET_USER_LASTNAME'
export const SET_USER_USERNAME = 'SET_USER_USERNAME';
export const SET_USER_EXCERPT = 'SET_USER_EXCERPT'
export const SET_USER_EMAIL = 'SET_USER_EMAIL'
export const SET_USER_NUMBER = 'SET_USER_NUMBER'
export const SET_USER_USERIMAGE = 'SET_USER_USERIMAGE'
export const SET_USER_ACTIVEPLAYLIST = 'SET_USER_ACTIVEPLAYLIST'
export const SET_USER_LASTSONG = 'SET_USER_LASTSONG'
export const SET_USER_LAST_SEEKTIME = 'SET_USER_LAST_SEEKTIME'
export const SET_USER_TOTALMINUTESLISTENED = 'SET_USER_TOTALMINUTESLISTENED'
export const SET_USER_TOTAL_PLAYS_COUNT = 'SET_USER_TOTAL_PLAYS_COUNT'
export const SET_USER_ROLE = 'SET_USER_ROLE'
export const SET_USER_TOTAL_QUIZE_POINTS = 'SET_USER_TOTAL_QUIZE_POINTS'
export const SET_USER_LAST_QUIZ_DATE = 'SET_USER_LAST_QUIZ_DATE'

//User state type
export const SET_SHOW_MY_ONLINE_STATUS = 'SET_SHOW_MY_ONLINE_STATUS';
export const SET_SHOW_OTHERS_COMMENTS = 'SET_SHOW_OTHERS_COMMENTS';
export const SET_ALLOW_RANDOM_QUIZ = 'SET_ALLOW_RANDOM_QUIZ';
export const SET_ARTIFICIAL_WEATHER = 'SET_ARTIFICIAL_WEATHER';

//other global state type
export const SET_ASTRONOMY_PICTURE = 'SET_ASTRONOMY_PICTURE';
export const SET_GLOBAL_LANGUAGE = 'SET_GLOBAL_LANGUAGE';
