//Main Application theme state type
export const SET_MUSIC_APP_DARKMODE = 'SET_MUSIC_APP_DARKMODE';
export const SET_MIX_ITEM_LOADING_SPINNER = 'SET_MIX_ITEM_LOADING_SPINNER';


export const SET_ONLINE_USERS_LIST = 'SET_ONLINE_USERS_LIST'

//Application stats states
export const SET_CUMMULATIVE_MINUTES_LISTENED = 'SET_CUMMULATIVE_MINUTES_LISTENED';
export const SET_COMMULATIVE_PLAYS_COUNT = 'SET_COMMULATIVE_PLAYS_COUNT';
export const SET_CUMMULATIVE_COMMENTS = 'SET_CUMMULATIVE_COMMENTS';
export const SET_TOTAL_USERS_COUNT = 'SET_TOTAL_USERS_COUNT';
export const SET_TOTAL_SHAZAM_COUNT = 'SET_TOTAL_SHAZAM_COUNT';
export const SET_HIGEST_FAVOURITES = 'SET_HIGEST_FAVOURITES';
export const SET_CUMMULATIVE_DOWNLOADS = 'SET_CUMMULATIVE_DOWNLOADS';
export const SET_CUMMULATIVE_QUIZ_ATTEMPTS = 'SET_CUMMULATIVE_QUIZ_ATTEMPTS';

//other global state type
export const SET_ASTRONOMY_PICTURE = 'SET_ASTRONOMY_PICTURE';
export const SET_GLOBAL_LANGUAGE = 'SET_GLOBAL_LANGUAGE';

//Intro JS allow the aside navigation to be drawn when its mobile device
export const SET_ASIDE_NAVIGATION_OPEN_APP_TOUR = 'SET_ASIDE_NAVIGATION_OPEN_APP_TOUR';
export const SET_ENABLE_APPLICATION_TOUR = 'SET_ENABLE_APPLICATION_TOUR'

// consider the below as the final code for the redux
export const SET_MAIN_APP_DARKMODE = 'SET_MAIN_APP_DARKMODE';
export const SET_THANOS_SNAP_ANIMATION = 'SET_THANOS_SNAP_ANIMATION';
export const SET_NOTIFIATION_TEXT_ITEM = 'SET_NOTIFIATION_TEXT_ITEM';
export const SET_ENABLE_GLOBAL_AUDIO_VISUALIZER = 'SET_ENABLE_GLOBAL_AUDIO_VISUALIZER';
export const SET_ENABLE_GLOBAL_ASTRONOMY_PICTURE = 'SET_ENABLE_GLOBAL_ASTRONOMY_PICTURE';
export const SET_ENABLE_GLOBAL_SHAZAM_SEARCH = 'SET_ENABLE_GLOBAL_SHAZAM_SEARCH';
export const SET_ENABLE_GLOBAL_DOWNLOAD_OPTION = 'SET_ENABLE_GLOBAL_DOWNLOAD_OPTION';
export const SET_ENABLE_GLOBAL_CALM_ANXIETY = 'SET_ENABLE_GLOBAL_CALM_ANXIETY';
export const SET_ENABLE_GLOBAL_ALLOW_USERS_SEE_OTHERS_ONLINE_ACTIVITY = 'SET_ENABLE_GLOBAL_ALLOW_USERS_SEE_OTHERS_ONLINE_ACTIVITY';