export const en = {
    //heade, footer, navbar items
    'admin': 'admin',
    'user': 'user',
    'dashboard': 'Dashboard',
    'signout': 'signout',
    'new-mix-by': 'new mix by',
    'new-message-from': 'new message from',
    'created-with': 'Created with',
    'by': 'by',
    'for-a-cool-fan-like-you': 'for a cool you',
    'music': 'Music',
    'message': 'Messages',
    'profile': 'Profile',
    'logout': 'Logout',
    'welcome': 'Welcome ',
    'about': 'About',
    'account': 'Account',
    'resume': 'Resume',
    'services': 'Services',
    'portfolio': 'Portfolio',
    'contact': 'Contact',

    //Dashboard both admin and user
    'total-minutes-listened': 'Total Minutes Listened',
    'total-played': 'Total Played',
    'downloaded': 'Downloaded',
    'favourites': 'Favourites',
    'total-comments': 'Total comments',
    'shazam-request': 'Shazam Request',
    'quiz-attempts': 'Quiz Attempts',
    'music-mix-performance': 'Music Mix Performance',
    'history-plays': 'History Plays',
    'favourites-list': 'Favourites Fist',
    'identified-songs': 'Identified Songs',
    'quiz-stats-points': 'Latest Mix Releases',
    'you-have': 'you have',
    'username': 'Username',
    'points': 'Points',
    'completion': 'Completion',
    'my-comments': 'My Comments',
    'songs-count':'Songs Count',
    'duration':'Duration',

    //Music section 
    'listeners-playlist': 'Listeners Playlist',
    'home': 'Home',
    'listeners': 'Listeners',
    'calm-your-anxiety': 'Calm your anxiety',
    'astronomy-picture-of-the-day': 'Astronomy picture of the day',
    'online-listeners': 'Online listeners',
    'previous': 'Previous',
    'forwad-30sec': 'Forward 30sec',
    'back-30sec': 'Back 30sec',
    'play': 'Play',
    'pause': 'Pause',
    'stop': 'Stop',
    'replay': 'Replay',
    'random': 'Random',
    'playlist': 'Playlist',
    'volume': 'Volume',
    'player-favourite': 'Player favourite',
    'fullscreen': 'Fullscreen',
    'visualizer': 'Visualizer',
    'download': 'Download',
    'seek': 'Seek',
    'choose-playlist': 'Choose Playlist',
    'default': 'Default',
    'comments': 'Comments',
    'liked-the-mix-leave-comment': 'Liked the mix ? Leave a comment.',
    'share-with-friends': 'Share with Friends',
    'reply': 'Reply',
    'edit': 'Edit',
    'delete': 'Delete',
    'your-comment': 'Your Comment',
    'cancel': 'Cancel',
    'successfully-added': 'successfully added',
    'to-your-favourites-list': 'to your favourites list',

    //Messages chat box
    'chat-rooms': 'Chat Rooms',
    'type-message': 'Type a message',
    'emoji': 'emoji',
    'send': 'send',
    'choose-room-to-join':'Choose Room to Join',
    'welcome-to-chat-room-about': 'Welcome to Chat Room about ',

    //Norifications
    'notifications': 'Notifications',

    //Profile
    'fullname': 'Fullname',
    'your-firstname': 'your firstname',
    'your-lastname': 'your lastname',
    'your-email': 'your email',
    'your-username': 'your username',
    'your-password': 'your password',
    'update': 'update',
    'mobile': 'mobile',
    'show-other-users-my-comments': 'show other users my comments',
    'show-other-listeners-my-online-status': 'show other listeners my online status',
    'allow-random-quiz': 'allow random quiz',
    'enable-artificial-weather': 'enable artificial weather',
    'music-player-theme': 'music player theme',
    'delete-my-account-together-with-data': 'delete my account together with data',
    'profile-information': 'Profile Information',
    'edit-profile': 'Edit Profile',
    'platform-settings': 'Platform Settings',
    'music-visualizer': 'Music Visualizer',
    'update-profile': 'Update profile',
    'close': 'Close',
    'your-phonenumber': 'Your Phone Nmber',
    'your-excerpt': 'Your Excerpt',
    'application-theme': 'Dark Application theme',
    'enabled': 'Enabled',
    'disabled' : 'Disabled',
    'Successfully-made-your-Online-Status':'Successfully made your online status',
    'Successfully-made-your-Comments':'Successfully made your comments',
    'Successfully':'Successfully',
    'Dark-Mode':'Dark Mode',
    'activated':'Activated',
    'deactivated': 'Deactivatefd',
    'visible': 'Visible',
    'hidden': 'Hidden',
    'audio-visualizer': 'Audio Visualizer',
    'are-your-sure':'Are you sure?',
    'delete-warning-text':'Once you have deleted your account theres no going back!',
    'success-deleted-text':'Poof! Your account has been deleted!',
    'success-canceled-text':'Pheew!! Your account is safe!',
    'your-generated-ai':'Your Generated Images',

    //About
    'for-fans-and-music-lovers': 'For Fans and Music Lovers',
    'for-developers-and-recruiters': 'For Developers and Recruiters',
    'support-and-good-course': 'Support and Good Course',

    //Footer
    'leave-comment': 'Leave comment',
    'play-pause': 'play pause',
    'click-to-identify': 'Click to Identify',

    //signup
    'email': 'Email',
    'password': 'Password',
    'number': 'Number',
    'remember-me': 'Remember me',
    'already-have-an-account-?': 'Already have an account?',

    //signin
    'name': 'Name',
    'i-agree-with-terms-and-conditions': 'I agree to with terms and conditions',
    'sign-in': 'sign in',
    'dont-have-an-account-?': 'Dont have an account',
    'sign-in-with-social-media-accounts': 'Sign in with social media accounts',

    //Guest Landing page
    'house-music-mix': 'House music mix',
    'click-here-to-sign-in': 'Click here to sign in or Demo App',
    'designed-by': 'Desgined by',

    //intro onBoarding Section
    'back': 'Back',
    'next': 'Next',
    'complete': 'Complete',
    'intro-text': 'I am so happy to have you here. There are a lot of Exciting things in store for you. Please take this tour that will inform on how to navigate the application it will only appear once on initial loading. But if you want to see it again you can hit play button on music section',
    'music-section': 'Music section',
    'music-section-text': 'This is the main reason you are here, the music section of the application. Apart from interacting with the audio controls of the music player you will also be able to have other cool stuff to play around with. Check out the about section to read a more detailed description of all features..',
    'music-section-navigation': 'Music Section Navigation',
    'music-section-navigation-text': 'This is the sub Navigation inside the music section that you can use to explore other cool sections inside it',
    'main-music-player': 'Main Music Player',
    'main-music-player-text': 'Here you will be able to launch and view the main music player which has even more selection of controls for the mix items and its playlist.',
    'quick-navigation': 'Notifications',
    'quick-navigation-text': 'Here you will be briefed on the latest notifications about the application.',
    'language-section': 'Language Section',
    'language-section-text': 'Here you will be able to select your favourite language to use in the application. More languages shall follow in later updates.',
    'footer-section': 'Footer Section',
    'footer-section-text': 'In this section you will be allowed to use a couple of extra features among quick music controls, Song recognition engine and volume of the mix item playing.',
    'main-navigation': 'Main Navigation',
    'main-navigation-text': 'This is the side Navigation to help you move around the entire application. This can be launched from the top Launcher in Mobile View',
    'dashboard-page': 'Dashboard Page',
    'dashboard-page-text': 'In here you will be able to see your usage statistics in the application.',
    'message-page': 'Message Page',
    'message-page-text': 'In here you will be able to communicate with each other if you allow online activity.  Theres a catch, after you close your browser your chat gets deleted. ',
    'notifications-page': 'Notifications Page',
    'notifications-page-text': 'In here you will be able to read any new and past notifications on any events that come up in the application.',
    'about-page': 'About Page',
    'about-page-text': 'Here you can read more about this application and the intricasies that came into its design and development. Also includes an explanation of what to expect in the application.',
    'profile-page': 'Profile Page',
    'profile-page-text': 'Here you will be able to change and update your personal profile upto including deleting your entire application with any data collected.',
    'logout-button': 'Logout Button',
    'logout-button-text': 'Well this is self explanatory hahah.',
    'lastly': 'Lastly',
    'lastly-text': 'Take your time and enjoy this master piece i have created for you. Have a great time and Shout me out whenever and wherever you can. Saisere!!',

    //application settings
    'There-is-an-error-accessing-the-Mix-Item':'There is an error accessing the Mix Item',
    'success': 'Success',
    'warning': 'Warning',
}