export const es = {
    //heade, footer, navbar items
    'admin': 'Administrador',
    'user': 'Usuario',
    'dashboard': 'Tablero',
    'signout': 'Desconectar',
    'new-mix-by': 'Una nueva mezcla de',
    'new-message-from': 'Un nuevo mensaje de',
    'created-with': 'Creado con',
    'by': 'por',
    'for-a-cool-fan-like-you': 'Para ti',
    'music': 'Música',
    'message': 'Mensaje',
    'profile': 'Perfil',
    'logout': 'Cerrar sesión',
    'welcome': 'bienvenido ',
    'about': 'sobre',
    'account': 'cuenta',
    'resume': 'curriculum vitae',
    'services': 'servicios',
    'portfolio': 'cartera',
    'contact': 'contactar con',

    //Dashboard both admin and user
    'total-minutes-listened': 'Minutos totales escuchados',
    'total-played': 'Mezclas totales reproducidas',
    'downloaded': 'Mezcla descargada',
    'favourites': 'Mezclas favoritas',
    'total-comments': 'Comentarios totales',
    'shazam-request': 'Solicitudes de Shazam',
    'quiz-attempts': 'Intentos de prueba',
    'music-mix-performance': 'Rendimiento de mezcla de música',
    'history-plays': 'Historia',
    'favoutes-list': 'Lista de favoritos',
    'identified-songs': 'Canciones identificadas',
    'quiz-stats-points': 'Últimos lanzamientos de mezclas',
    'you-have': 'tú tienes',
    'username': 'Nombre de usuario',
    'points': 'Puntos',
    'completion': 'Terminación',
    'my-comments': 'Mis comentarios',
    'genre':'',
    'songs-count':'recuento de canciones',
    'duration':'duración',

    //Music section 
    'listeners-playlist': 'Lista de reproducción de oyentes',
    'home': 'Página principal',
    'listeners': 'Oyentes',
    'calm-your-anxiety': 'Calma tu ansiedad',
    'astronomy-picture-of-the-day': 'foto astronomia del dia',
    'online-listeners': 'Oyentes en línea',
    'forwad-30sec': 'Mezcla directa 30 segundos',
    'back-30sec': 'Volver a mezclar 30 segundos',
    'play': 'Tocar',
    'pause': 'Pausa',
    'stop': 'Dejar',
    'replay': 'Repetir',
    'random': 'Barajar',
    'playlist': 'Lista de reproducción',
    'volume': 'Volumen',
    'player-favourite': 'Favorita',
    'fullscreen': 'Pantalla completa',
    'visualizer': 'Visualizador',
    'download': 'Descargar',
    'seek': 'Solicitar',
    'choose-playlist': 'elegir la lista de reproducción',
    'default': 'por defecto',
    'comments': 'comentarios',
    'liked-the-mix-leave-comment': '¿Te ha gustado la mezcla? Deja un comentario',
    'share-with-friends': 'compartir con los amigos',
    'reply': 'respuesta',
    'edit': 'editar',
    'delete': 'borrar',
    'your-comment': 'su comentario',
    'cancel': 'cancelar',
    'successfully-added': 'añadido con éxito',
    'to-your-favourites-list': 'a su lista de favoritos',

    //Messages chat box
    'chat-rooms': 'Salas de chat',
    'type-message': 'Escribir mensaje',
    'emoji': 'Emoticonos',
    'send': 'Enviar',
    'choose-room-to-join':'Elija la sala para unirse',
    'welcome-to-chat-room-about': 'Bienvenida a la sala de chat sobre',

    //Norifications
    'notifications': 'Notificaciones',

    //Profile
    'fullname': 'Nombre completo',
    'your-firstname': 'primer nombre',
    'your-lastname': 'Apellido',
    'your-email': 'Email',
    'your-username': 'Usuario',
    'your-password': 'Clave',
    'update': 'Actualizer',
    'mobile': 'Movil',
    'show-other-users-my-comments': 'Mostrar commentarios',
    'show-other-listeners-my-online-status': 'Mostrar el estado en linea',
    'allow-random-quiz': 'Prueba aleatoria',
    'enable-artificial-weather': 'Habilitar tiempo en vivo',
    'application-theme': 'Tema de la aplicacion',
    'music-player-theme': 'Tema del reproductor de musica',
    'delete-my-account-together-with-data': 'Eliminar datos de la cuenta',
    'profile-information': 'información sobre el perfil',
    'edit-profile': 'editar perfil',
    'platform-settings': 'configuración de la plataforma',
    'music-visualizer': 'visualizador de música',
    'update-profile': 'actualizar el perfil',
    'close': 'cerrar',
    'your-phonenumber': 'su número de teléfono',
    'your-excerpt': 'votre extrait',
    'enabled': 'habilitado',
    'disabled': 'discapacitados',
    'Successfully-made-your-Online-Status': 'Realizó con éxito su estado en línea',
    'Successfully-made-your-Comments': 'Realizó con éxito sus comentarios',
    'Successfully': 'Con éxito',
    'Dark-Mode': 'modo oscuro',
    'activated': 'activado',
    'deactivated': 'desactivado',
    'audio-visualizer': 'visualizador de audio',
    'are-your-sure':'¿Está seguro?',
    'delete-warning-text':'Una vez que hayas eliminado tu cuenta, no hay vuelta atrás.',
    'success-deleted-text':'¡Puf! Tu cuenta ha sido eliminada.',
    'success-canceled-text':'¡¡Feew!! ¡Tu cuenta está a salvo!',
    'your-generated-ai':'Sus imágenes de IA generadas',

    //About
    'for-fans-and-music-lovers': 'Para aficionados y amantes de la música',
    'for-developers-and-recruiters': 'para desarrolladores y reclutadores',
    'support-and-good-course': 'apoyo y buen curso',

    //Footer
    'leave-comment': 'deja un comentario',
    'previous': 'anterior',
    'play-pause': 'jugar pausa',
    'next': 'siguiente',
    'click-to-identify': 'haga clic para identificar',

    //signup
    'email': 'Email',
    'password': 'Clave',
    'number': 'Telefono',
    'remember-me': 'Recuerdame',
    'already-have-an-account-?': 'Tener una cuenta',

    //signin
    'name': 'Nombre',
    'i-agree-with-terms-and-conditions': 'Estoy de acuerdo los terminos y condiciones',
    'sign-in': 'Registarse',
    'dont-have-an-account-?': 'Sin cuenta',
    'sign-in-with-social-media-accounts': 'Iniciar sesion con las redes sociales',

    //Guest Landing page
    'house-music-mix': 'mezcla de música house',
    'click-here-to-sign-in': 'haga clic aquí para iniciar sesión',
    'designed-by': 'diseñado por',

    //intro onBoarding Section
    'back': 'volver',
    'complete': 'completo',
    'intro-text': 'Estoy muy feliz de tenerte aquí. Hay un montón de cosas emocionantes en el almacén para usted. Por favor, haz este recorrido que te informará sobre cómo navegar por la aplicación, sólo aparecerá una vez en la carga inicial. Pero si quieres verlo de nuevo puedes pulsar el botón de reproducción en la sección de música',
    'music-section': 'sección de música',
    'music-section-text': 'Esta es la razón principal por la que estás aquí, la sección de música de la aplicación. Además de interactuar con los controles de audio del reproductor de música, también podrás tener otras cosas interesantes con las que jugar. Consulta la sección "Acerca de" para leer una descripción más detallada de todas las características.',
    'music-section-navigation': 'navegación por la sección de música',
    'music-section-navigation-text': 'Esta es la subnavegación dentro de la sección de música que puedes utilizar para explorar otras secciones interesantes dentro de ella',
    'main-music-player': 'reproductor de música principal',
    'main-music-player-text': 'Aquí podrás lanzar y ver el reproductor de música principal que tiene aún más selección de controles para los elementos de mezcla y su lista de reproducción.',
    'quick-navigation': 'navegación rápida',
    'quick-navigation-text': 'Aquí se le informará de las últimas notificaciones sobre la aplicación.',
    'language-section': 'selección de idioma',
    'language-section-text': 'Aquí podrá seleccionar su idioma favorito para utilizarlo en la aplicación. En posteriores actualizaciones se añadirán más idiomas.',
    'footer-section': 'sección del pie de página',
    'footer-section-text': 'En esta sección podrás utilizar un par de funciones extra entre los controles rápidos de música, el motor de reconocimiento de canciones y el volumen del elemento de mezcla que se está reproduciendo.',
    'main-navigation': 'navegación principal',
    'main-navigation-text': 'Esta es la navegación lateral que le ayuda a moverse por toda la aplicación. Se puede lanzar desde el lanzador superior en la vista móvil',
    'dashboard-page': 'página del tablero',
    'dashboard-page-texxt': 'Aquí podrás ver tus estadísticas de uso en la aplicación.',
    'message-page': 'mensaje pa',
    'message-page-text': 'Aquí podréis comunicaros entre vosotros si permitís la actividad online.  Hay una pega, después de cerrar el navegador el chat se borra.',
    'notifications-page': 'página de notificaciones',
    'notifications-page-text': 'Aquí podrás leer las notificaciones nuevas y pasadas sobre cualquier evento que surja en la aplicación.',
    'about-page': 'página Acerca de',
    'about-page-text': 'Aquí puede leer más sobre esta aplicación y los entresijos de su diseño y desarrollo. También incluye una explicación de lo que se puede esperar de la aplicación.',
    'profile-page': 'página de perfil',
    'profile-page-text': 'Aquí podrá cambiar y actualizar su perfil personal hasta incluso eliminar toda su solicitud con los datos recogidos.',
    'logout-button': 'botón de cierre',
    'logout-button-text': 'Bueno, esto se explica por sí mismo.',
    'lastly': 'por último',
    'lastly-text': 'Tómate tu tiempo y disfruta de esta obra maestra que he creado para ti. Pasadlo bien y gritadme cuando y donde podáis.',

    //application settings
    'There-is-an-error-accessing-the-Mix-Item': 'Hay un error al acceder al elemento de mezcla',
    'success': 'éxito',
    'warning': 'advertencia',
}
