export const fr = {
    //heade, footer, navbar items
    'admin': 'administrateur',
    'user': 'utilisateur',
    'dashboard': 'tableau de bord',
    'signout': 'se deconnecter',
    'new-mix-by': 'nouveau mix par',
    'new-message-from': 'nouveau message de',
    'created-with': 'créé avec',
    'by': 'par',
    'for-a-cool-fan-like-you': 'Pour vous',
    'music': 'musique',
    'message': 'Message',
    'profile': 'profil',
    'logout': 'Déconnexion',
    'welcome': 'bienvenue à ',
    'about': 'à propos de',
    'account': 'compte',
    'resume': 'CV',
    'services': 'services',
    'portfolio': 'portefeuille',
    'contact': 'contacter',

    //Dashboard both admin and user
    'total-minutes-listened': 'nombre total de minutes écoutées',
    'total-played': 'total joué',
    'downloaded': 'Téléchargé',
    'favourites': 'favoris',
    'total-comments': 'nombre total de commentaires',
    'shazam-request': 'demande shazam',
    'quiz-attempts': 'tentatives de quiz',
    'music-mix-performance': 'performance de mixage musical',
    'history-plays': 'pièces d\'histoire',
    'favoutes-list': 'liste des favoris',
    'identified-songs': 'chansons identifiées',
    'quiz-stats-points': 'Dernières sorties de mix',
    'you-have': 'vous avez',
    'username': 'nom d\'utilisateur',
    'points': 'aiguillage',
    'completion': 'achèvement',
    'my-comments': 'mes commentaires',
    'songs-count':'nombre de chansons',
    'duration':'durée',

    //Music section 
    'listeners-playlist': 'liste de lecture des auditeurs',
    'home': 'domicile',
    'listeners': 'Auditeurs',
    'calm-your-anxiety': 'calmer votre anxiété',
    'astronomy-picture-of-the-day': 'image astronomique du jour',
    'online-listeners': 'auditeurs en ligne',
    'forwad-30sec': 'avant 30 sec',
    'back-30sec': 'retour 30 sec',
    'play': 'jouer',
    'pause': 'pause',
    'stop': 'arrêter',
    'replay': 'rejouer',
    'random': 'aléatoire',
    'playlist': 'playlist',
    'volume': 'volume',
    'player-favourite': 'joueur préféré',
    'fullscreen': 'plein écran',
    'visualizer': 'Visualizer',
    'download': 'télécharger',
    'seek': 'chercher',
    'choose-playlist': 'choisir la liste de lecture',
    'default': 'por defecto',
    'comments': 'commentaires',
    'liked-the-mix-leave-comment': 'Vous avez aimé le mélange ? Laissez un commentaire',
    'share-with-friends': 'partager avec des amis',
    'reply': 'réponse',
    'edit': 'modifier',
    'delete': 'supprimer',
    'your-comment': 'votre commentaire',
    'cancel': 'annuler',
    'successfully-added': 'ajouté avec succès',
    'to-your-favourites-list': 'à votre liste de favoris',

    //Messages chat box
    'chat-rooms': 'Salles de discussions',
    'type-message': 'type de message',
    'emoji': 'emoji',
    'send': 'Envoyer',
    'choose-room-to-join':'Choisissez la salle à rejoindre',
    'welcome-to-chat-room-about': 'Bienvenue sur le chat à propos de',

    //Norifications
    'notifications': 'Notifications',

    //Profile
    'fullname': 'nom complet',
    'your-firstname': 'prénom',
    'your-lastname': 'nom de famille',
    'your-email': 'email',
    'your-username': 'nom d\'utilisateur',
    'your-password': 'mot de passe',
    'update': 'mettre à jour',
    'mobile': 'mobile',
    'show-other-users-my-comments': 'montrer aux autres mes commentaires',
    'show-other-listeners-my-online-status': 'afficher aux autres auditeurs mon statut en ligne',
    'allow-random-quiz': 'autoriser le quiz aléatoire',
    'enable-artificial-weather': 'permettre un temps artificiel',
    'application-theme': 'thème de l\'application',
    'music-player-theme': 'thème du lecteur de musique',
    'delete-my-account-together-with-data': 'supprimer les données du compte',
    'profile-information': 'informations sur le profil',
    'edit-profile': 'modifier le profil',
    'platform-settings': 'paramètres de la plate-forme',
    'music-visualizer': 'visualisateur de musique',
    'update-profile': 'profil de mise à jour',
    'close': 'fermer',
    'your-phonenumber': 'votre numéro de téléphone',
    'your-excerpt': 'votre extrait',
    'enabled': 'activé',
    'disabled': 'désactivé',
    'Successfully-made-your-Online-Status': 'Vous avez réussi à créer votre statut en ligne',
    'Successfully-made-your-Comments': 'Vous avez réussi à faire vos commentaires',
    'Successfully': 'Avec succès',
    'Dark-Mode': 'mode sombre',
    'activated': 'activé',
    'deactivated': 'désactivé',
    'audio-visualizer': 'audio visuel',
    'are-your-sure':'¿Está seguro?',
    'delete-warning-text':'Une fois que vous avez supprimé votre compte, vous ne pouvez plus revenir en arrière !',
    'success-deleted-text':'Pouf ! Votre compte a été supprimé !',
    'success-canceled-text':'Pheew !! Votre compte est en sécurité !',
    'your-generated-ai':'Vos images AI générées',

    //About
    'for-fans-and-music-lovers': 'pour les fans et les mélomanes',
    'for-developers-and-recruiters': 'pour les développeurs et les recruteurs',
    'support-and-good-course': 'soutien et bon cours',

    //Footer
    'leave-comment': 'Écrire un commentaire',
    'previous': 'précédent',
    'play-pause': 'jouer pause',
    'next': 'prochain',
    'click-to-identify': 'cliquer pour identifier',

    //signup
    'email': 'email',
    'password': 'mot de passe',
    'number': 'nombre',
    'remember-me': 'souvenez-vous de moi',
    'already-have-an-account-?': 'vous avez déjà un compte',

    //signin
    'name': 'nom',
    'i-agree-with-terms-and-conditions': 'accepter les termes et conditions',
    'sign-in': 'Connexion',
    'dont-have-an-account-?': 'n\'ont pas de compte',
    'sign-in-with-social-media-accounts': 'connectez-vous avec des comptes de médias sociaux',

    //Guest Landing page
    'house-music-mix': 'mix house',
    'click-here-to-sign-in': 'cliquez ici pour vous connecter',
    'designed-by': 'conçu par',

    //intro onBoarding Section
    'back': 'revenir',
    'complete': 'complet',
    'intro-text': 'Je suis si heureux de vous avoir ici. Il y a beaucoup de choses excitantes en réserve pour vous. Veuillez suivre cette visite qui vous informera sur la façon de naviguer dans l\'application. Elle n\'apparaîtra qu\'une fois lors du chargement initial. Mais si vous voulez la revoir, vous pouvez appuyer sur le bouton de lecture de la section musique.',
    'music-section': 'section musique',
    'music-section-text': 'C\'est la raison principale pour laquelle vous êtes ici, la section musique de l\'application. En plus d\'interagir avec les commandes audio du lecteur de musique, vous pourrez également jouer avec d\'autres éléments. Consultez la section "à propos" pour lire une description plus détaillée de toutes les fonctions...',
    'music-section-navigation': 'navigation section musique',
    'music-section-navigation-text': 'Il s\'agit de la sous-navigation à l\'intérieur de la section musique que vous pouvez utiliser pour explorer d\'autres sections intéressantes.',
    'main-music-player': 'joueur principal de musique',
    'main-music-player-text': 'Ici, vous pourrez lancer et afficher le lecteur de musique principal qui dispose d\'un choix encore plus large de commandes pour les éléments de mixage et sa liste de lecture.',
    'quick-navigation': 'navigation rapide',
    'quick-navigation-text': 'Vous y serez informé des dernières notifications concernant l\'application.',
    'language-section': 'sélection de la langue',
    'language-section-text': 'Vous pourrez y sélectionner votre langue préférée à utiliser dans l\'application. D\'autres langues suivront dans les mises à jour ultérieures.',
    'footer-section': 'section pied de page',
    'footer-section-text': 'Dans cette section, vous serez autorisé à utiliser quelques fonctions supplémentaires parmi les commandes musicales rapides, le moteur de reconnaissance des chansons et le volume de l\'élément de mixage en cours de lecture.',
    'main-navigation': 'navigation principale',
    'main-navigation-text': 'Il s\'agit de la navigation latérale qui vous aide à vous déplacer dans l\'ensemble de l\'application. Elle peut être lancée à partir du lanceur supérieur en vue mobile.',
    'dashboard-page': 'page Tableau',
    'dashboard-page-texxt': 'Vous pourrez y consulter les statistiques d\'utilisation de l\'application.',
    'message-page': 'page de massage',
    'message-page-text': 'Ici, vous pourrez communiquer entre vous si vous autorisez l\'activité en ligne.  Il y a un hic, après avoir fermé votre navigateur, votre chat est supprimé.',
    'notifications-page': 'page Notifications',
    'notifications-page-text': 'Vous pourrez y lire toutes les notifications nouvelles et passées sur les événements qui apparaissent dans l\'application.',
    'about-page': 'page À propos',
    'about-page-text': 'Vous trouverez ici plus d\'informations sur cette application et les subtilités qui ont présidé à sa conception et à son développement. Vous y trouverez également une explication de ce que vous pouvez attendre de l\'application.',
    'profile-page': 'page de profil',
    'profile-page-text': 'Vous pourrez y modifier et mettre à jour votre profil personnel jusqu\'à la suppression de l\'ensemble de votre candidature et de toutes les données recueillies.',
    'logout-button': 'bouton de déconnexion',
    'logout-button-text': 'Eh bien, c\'est auto-explicatif hahah.',
    'lastly': 'enfin',
    'lastly-text': 'Prenez votre temps et appréciez ce chef-d\'œuvre que j\'ai créé pour vous. Passez un bon moment et faites-moi signe quand et où vous le pouvez.',

    //application settings
    'There-is-an-error-accessing-the-Mix-Item': 'Une erreur s\'est produite lors de l\'accès à l\'élément de mélange',
    'success': 'succès',
    'warning': 'avertissement',
}