const en = { 
    //heade, footer, navbar items
    'admin'  :   '',
    'user'  :   '',
    'dashboard'  :   '',
    'signout'  :   '',
    'new-mix-by'  :   '',
    'new-message-from'  :   '',
    'created-with'  :   '',
    'by'  :   '',
    'for-a-cool-fun-like-you'  :   '',
    'dashboard'  :   '',
    'music'  :   '',
    'message'  :   '',
    'notifications'  :   '',
    'profile'  :   '',
    'logout' : '',
    //Dashboard both admin and user
    'total-minutes-listened'  :   '',
    'total-played'  :   '',
    'downloaded'  :   '',
    'favourites'  :   '',
    'total-comments'  :   '',
    'shazam-request'  :   '',
    'quiz-attempts'  :   '',
    'music-mix-performance'  :   '',
    'history-plays'  :   '',
    'favoutes-list'  :   '',
    'identified-songs'  :   '',
    'quiz-stats-points'  :   '',
    'you-have'  :   '',
    'username'  :   '',
    'points'  :   '',
    'completion'  :   '',
    'my-comments'  :   '',
    //Music section 
    'listeners-playlist'  :   '',
    'home'  :   '',
    'listeners'  :   '',
    'calm-your-anxiety'  :   '',
    'astronomy-picture-of-the-day'  :   '',
    'online-listeners'  :   '',
    'next'  :   '',
    'previous'  :   '',
    'forwad-30sec'  :   '',
    'back-30sec'  :   '',
    'play'  :   '',
    'pause'  :   '',
    'stop'  :   '',
    'replay'  :   '',
    'random'  :   '',
    'playlist'  :   '',
    'volume'  :   '',
    'player-favourite'  :   '',
    'fullscreen'  :   '',
    'visualizer'  :   '',
    'download'  :   '',
    'seek'  :   '',
    //Messages chat box
    'chat'  :   '',
    'type-message'  :   '',
    'emoji'  :   '',
    'send'  :   '',
    //Norifications
    'notifications'  :   '',
    //Profile
    'fullname'  :   '',
    'your-firstname'  :   '',
    'your-lastname'  :   '',
    'your-email'  :   '',
    'your-username'  :   '',
    'your-password'  :   '',
    'update'  :   '',
    'mobile'  :   '',
    'show-other-users-my-comments'  :   '',
    'show-other-listeners-my-online-status'  :   '',
    'allow-random-quiz'  :   '',
    'enable-artificial-weather'  :   '',
    'application-theme'  :   '',
    'music-player-theme'  :   '',
    'delete-my-account-together-with-data'  :   '',
    //signup
    'email'  :   '',
    'password'  :   '',
    'number'  :   '',
    'remember-me'  :   '',
    'already-have-an-account-?'  :   '',
    //signin
    'name'  :   '',
    'email'  :   '',
    'password'  :   '',
    'i-agree-with-terms-and-conditions'  :   '',
    'sign-in'  :   '',
    'dont-have-an-account-?'  :   '',
    'sign-in-with-social-media-accounts'  :   '',
 }

 export default en;