import React from 'react'

import Tab from 'react-bootstrap/Tab';
import Tabs from 'react-bootstrap/Tabs';

// import the file to allow changing of the language manually
import { useTranslation } from "react-i18next";

import { Link } from 'react-router-dom';


export default function About() {

    //initiate tge translator
    const { t } = useTranslation();


    return (
        <div style={{ height: "86vh", overflow: "auto" }}>
            <Tabs
                defaultActiveKey="fans"
                id="justify-tab-example"
                className="mb-1"
                justify
            >
                <Tab eventKey="fans" title={t("for-fans-and-music-lovers")}>
                    Hello there glad you made it. I love you so much that i decided to create this amazing application for you. Lets be honest and realistic your here because you already know me or you were coarsed by the social inter-web into joining. Well either way your time shall not be wasted nor shall it be disappointed. With this system comes a bunch of features that i can guarantee you will grasp a good chunk of your attention. You know me for being a self proclaimed Disk Jockey(DJ), i Have being making mixes since back in high school. Some of you must have heard a couple of them and might want to listen to them again if not again and again, lucky you since i was keeping them since while back in total they are 50, Jeez thats big number i know hehe, even better for you who have heard some of them and know what is instore for you in the ones you havent. I recently gave more priority to House and Edm genre since they have been neglected quite abit in My country. But more genres shall follow obviously.

                    I decided to build this application since i didn’t like some of the services i was getting from some platforms i have been using before(i wont name them), and it hit me am Software Engineer and hence can do something about it. So i took very long break from the social life so i can focus on something that can be cool and vuala here we are. I have designed and developed this application wholey to address most of the needs that I couldn’t be offered by those platforms and added even more sophisticated features on top of it so that it stands out or addresses the attention magnet I was referring to early on. Here you will be able to download or listen to those mixes live and have a cool immersion while your at it. For those of you who are techy and would like to get to know the intricacies that come into the realization of this system then head over to the developers section and youl get to see what i used to achieve this note here your alone haha. You can also head over to my youtube channel (Toroyteachs) to see me describe and commentate on every feature and also a basic tutorial around the application.

                    Enough intro let me talk about what to expect. On the dashboard page you will get to see you stats for the entire time you will be on the application from listening to downloaded to minutes listened to comments your made on a mix item etc.
                    On the Music section being the main reason why we are here. You will be able to select the mix item to listen to wait couple seconds to have it buffer then you can listen them. you will be able to favorite some mix items so that you can select that favorite playlist and only listen to the selected ones. You can randomize the playlist, you can replay the mix item after it has finished so you can enjoy it in loo. You will be able to select an audio visualizer of your choice either Bars Spectrum or Circular Audio waves, but only if you have enabled visualizations in the profile section otherwise i somehow find the default 3 waves with the colors red blue and green to be soothing and has a calming effect when they animate. I will add more visualization selections in future. You will be able to seek forward and back(something some platform offer as payed version similar to micro transaction something i do not like haha). there is also a back 30sec and forward 1min button to move precisely to your desired  position. I have also implemented cookies so that next time when you log in you can resume from where you were without any hicks, so do accept my cookies request hehe. BTW the music section has its own navigation that you can move about so you can also appreciate what other features i have in-store for you. This include Online (Listeners) which shall make you be able to see other logged in users and what exact mix they would be listening to at that time. This is as close as other users can come to each other apart from commenting which i shall mention later. But don't dispare if your an introvert like i am for i have made it such that you can go the profile section and have this feature disabled meaning you wont be able to see other user online activiy and also they wont be able to see yours. So choice shall be yours always. This is almost similar to online status in any social media platform WhatsApp as an example.

                    Calm your anxiety where you will be provided with a video that is calming and has nice audio playing in the background, so you will have to hit play and the music shall stop if you want to here the sounds but ideally i think the video itself without the sounds can be cool. But still choice remains yours.

                    Picture of the day which is cool high resolution image of NASA that they take using there equipments and provide them to me together with there description and title. This photos change daily which each day bringing an even cooler image. so be sure to login in daily to get to see them hehe.

                    You will be able to give me a comment on the mix time and reply to other users comments about the same and have a nested conversation right there, i think this is among the main reasons i built this application so i can get the feedback from you people. You will also in your profile section be able to disable this so that only you and i can see the comments you have written. Note this option is a one way option such that you if you disable that feature the comments from that time hence forth shall take the effect and vice varsa.


                    There is this cool but experimental feature which am still debating on implementing, its a random music quiz where youl be able to choose whether to participate or not should you accept it youll be presented with a random old-school instrumental audio music for 10 seconds and your job will be to identify it. if you get it right you will be awarded points and ranked among other users and the more points you accumulate then you will be able to redeem them to get cool customization on the entire application. This includes dynamic themes, cool avatars for profile pictures etc. This is subject to consultation in my head haha.


                    In the Messages section will be able to DM me since this is not a social media platfiorm all messages shall be going to me directly so we can talk and you can share you ideas or opinions to me easily.
                    Notifications is quite self explanatory. Youl get all notifications on any new content uploaded or any communication that will be made that concerns the application.

                    And thus the About section which is for this part now where you are and will get to read about this application.
                    On the Account section we have the profile and the logout. i wont talk about the Logout but in the profile section is where your settings are and where you can update your profile details as well.

                    Since i would have collected your information and some Data then good development practice dictate that i make it able for you to delete your details, and hence i have given you an option to delete your account and all your data that i have collected. I have also made this decision a cool one haha. try and delete your account and see what happens, its a bitter sweet experience.


                    You should have or will notice that in all my mixes i don’t have any drops of my initials or my names anywhere, its just minutes long of straight music without interruptions. I personally don't like that idea, i like anonymity but then again i should make people be able to identify the person responsible behind this, so this application should do that part for me haha. Also you’l note on the cover images i have chosen for the mix items are cool animal paintings. Ill give you a hint they are not animals but people.

                    Ayaya almost forgot i have a song recognition system built into this application, you can call it shazam haha. should you be listening to a song and you dont know its details just hit the shazam button in the footer section and let me handle the recognition part for you. i will then store this song in a list that will populate in the dashboard for you reference. Btw i took that Mt Rongai photo in the profile and landing section with an apocalyptic effect, pretty cool huh.

                    There is also a multi lingual feature that i have added so if your from another not English speaking country you can change it to your own and continue enjoying the application, you can also change to you favorite international language and learn as you navigate around the application.

                    Please Enjoy my work and shout it out for me for that's the much appreciation i could ask for. i took 6 months developing and designing it just for you. Finally do not be selfish and share this work to your peers and friends for i am sure at most 3 mixes may impress them not to give me gangsta points but to make you enjoy and cure your boredom for a little while. My portfolio website is https://toroyteach.com and the music application website is https://music.toroyteach.com
                </Tab>
                <Tab eventKey="devs" title={t("for-developers-and-recruiters")}>
                    In this application that i was really looking forward to releasing, i have used alot of tech stack that have brought its reality. i will start with rationale that made me want to create this applicatinon and how i designed it all the way to its finish. i will include a youtube video that i will be commentaring on the code in the IDE and how they work with each other. I have been a DJ for a while now say over 10 years, i know the first thing that comes to your mind is commercialisation of that service, well i took a whole different path. I had decided i was going to be my own dj and since i like alot of music and my knowledge base of msic goes all the way back to before i was born. It all started when i was a young one and my older very much older siblings would undisputedly take control of any electronics and i was a mere courier service in the house. During this time i would listen to the music playing on the radio or any media player, I would take a keen interest in the beats and the rythme in how they follow each other in a reppetitive pattern. A few years later when my music knowledge matured, i got to listen to an instrumental of a famous song i had kept repeating on my sisters disc man from Nairobi to Kitale, the song grew in me i think i memorised all the lyrics R-Kelly was saying it was his song haha. As time and years went by i learned about Virtual Dj and its intricasies and started making my own mixes. Some of them having rookie mistakes and BPM mismatches. am sure youl get to here how i sucked long time ago haha.I become better and good at it. While all this was going on i was going to school and also living another life in the society. I did Computer science in University, I took an interest in programming leading me here. Because i have been making this music mixes and storing them i tought why not make an appliication which would show case my skills in this fields. Programming being the main priority here i decided to make the application as cool and as intuitive as i can make it be. I have conflicting goals that guided me to making this application. I hope by the end of it all both myself and the intended users of this application will be impressed if not slightly satisfied. One of this goals was to market and show case my skill in the programming realm. the other core goal was to give my fans a very cool sophisticated and satisfying applicatino that will at the very list get bit of there attention. I hope to atleast achieve one hehe.
                    Enough said now to the flesh of this text. In this frontend application i used Javascript framework (React JS). I have no particular reason for choosing this one, i generally have a liking to javascript being a language that manipulates DOM elements smoothly and also being a great use case of a single page application. Since most of the intereation in the application is going to be user center together with there data then i tought an SPA would be a great solution to this. Inside this React framework i have used atlease all the core features and implementatino of Javascript language having being modified in the React Realm.I have use the following hooks; Reducer, Context, States. Canvas element to have an audio visualizer similar to those bars and waves that you would see in a music player but this on in my application is the analysis of the audio nodes as they are playing. This data is extrapolated and drawn on a canvas element and clear every time to give the cool animation.Multilingual support, this was especially since music is not country based but international comodity then i thought i shouldnt be biased but have multiple language support on the application so that other users from other parts of the world could sign in and enjoy as well. Among the features or the implementations that i have added in the frontend include a dark mode selection. Chart js which helps me visualize how the users are interating with my content. on the backend side i have also implenented an API to google console which i get data on how the application is doing as SEO is concerned. Not that i want to rank or anything but since its a tool with data that be great to use also when i get an employer with such needs i can easily adapt. There is also use of FETCH API that gets data on NASA's astronomy picture of the day together with its descriotion and displays them. I am a fun of photography and nature as general, so i thoought is a good place to get this images and show to the fans and users, they are cool images either way. I will be talking about the backend side of this application when am finished with it. I use and am fan of regular expressions, this is my go to for form validation. i recently found and appreciated how they have been used all over in our development environments. SO i have implemented its uses in all all input fields in this application. I have also used cookies to store last song and time played, the mode that was set but use which does not require database storage.
                </Tab>
                <Tab eventKey="support" title={t("support-and-good-course")}>
                    HeHe now that you are here. I am quite sure there many good souls who like to see others do better or good. if your that kind or person why not extend that curtesy and donate to my patreon. i have a plee written and described there. otherwise i enjoy and love what i do i wont stop neither loose motivation. but i just though why not put it there. Fun fact in all of my mixes you will not hear my nome dropped anywhere
                    <br/><a className="text-primary text-gradient font-weight-bold" href='https://www.patreon.com/toroyteach'>Patreon</a>
                </Tab>
            </Tabs>
        </div>
    )
}
