import React from 'react'

import Tab from 'react-bootstrap/Tab';
import Tabs from 'react-bootstrap/Tabs';


export default function About() {
    return (
        <div style={{ height: "86vh", overflow: "auto" }}>
            <Tabs
                defaultActiveKey="fans"
                id="justify-tab-example"
                className="mb-1"
                justify
            >
                <Tab eventKey="fans" title="For Fans and Music Lovers">
                    I have created this application for you. I love you so much otherwise we woudnt be here. Am pretty sure some or most of you know me already and how my love or passion for music as been. 
                    Well we can just say its about damn time that i put up something cool. I had a quick thinking that maybe perhaps you could be need of some if not all of my mixes. 
                    Your are only here if you have heard them or about them or you have be coarsed into joining haha. Well welcome i have curated all of my mixes since i was rookie in this field till now and moving forward you shall be getting notification of any new content that i will be posting. 
                    This application i have disged and developed. You can check developers section if are abit interested but i can sure you you will suffer alone haha. 
                    Here you will get to enjoy not only my mixes but other cool stuff the application has to offer you. There is a calm your anxiety section with cool endless loop video and claming soothing sound playing in the backgrounf i would suggest playing using headphones if not earphone for maximum immersion. 
                    You can go and check out a cool astronomy pictures of the day with its description. i can assure you they are cool images and high resolution. 
                    This images shall be changing daily to give you different one daily. Be sure to login daily hehe. Should you enable the show my only activity status on your profile then you will be able to see other online users who are currently logged in and you will alos be able to see what mixe item they are currently listening to. 
                    Should you feel like you would like to give a comment on a certain piece of mix then feel free to do so in the comments page of the individual mix item. 
                    I for the online introverts i have you back. in the profile you will be able to diable and enanle visibility of your comments such that your comments shall not be seen by others but only myself. 
                    Note this feature is one way such that past actions will not be capture but change of state of that setting. Will this is still an experimental feature you will be able to have a random quize on the main music section where you will be presented with an instrumental of a famous oldschool music then have 10 seconds to be able to identify it. if you get it right you stand to get points which is redeamable with cool customisations of the entire application and having this settings or selection persisted.also there will be a score board where you will be ranked among other users. The most important this is Data collection. you will be able to delete your account and all the data that i will have collected about you any time you feel like. note this action is also irreversible. On the Dasboard you will be able to see your music application stats and have an over view of yout usage. Almost forgot hehe, there is a shazam feauture for you. Should you feel like the song your listening to is kind of peculiar and would to know what is it if you didnt then hit the search button and let me handle that for you. I will try to identify the song for you and show you then write this list down for you for future reference. Beacuse am banking on atleast one or atmost 3 mixes will please you then you can hit favourite button and have them curated on a favourites playlist so you only listen to those only. You can DM me if you have anything or any inquiries you would like in this application directly. Ohh and i took that Mt Rongai apocalyptic photo. PLease enjoy this work of beauty i love her so much. i would mean alot if i could get a shoutout and also if you could share this to others so we could all enjoy good music. Noticed i dont have a drop name in the mixes hehe.
                </Tab>
                <Tab eventKey="devs" title="For Developers and Requitors">
                    In this application that i was really looking forward to releasing, i have used alot of tech stack that have brought its reality. i will start with rationale that made me want to create this applicatinon and how i designed it all the way to its finish. i will include a youtube video that i will be commentaring on the code in the IDE and how they work with each other. I have been a DJ for a while now say over 10 years, i know the first thing that comes to your mind is commercialisation of that service, well i took a whole different path. I had decided i was going to be my own dj and since i like alot of music and my knowledge base of msic goes all the way back to before i was born. It all started when i was a kind my older very much older siblings would undisputedly take control of any electronic and i was a mere curious service in the house. During this time i would listen to the music playing on the radio or any media player, I would take a keen interest in the beats and the rythme in how they follow each other in a reppetitive pattern. A few years later when my music knowledge matured, i got to listen to an instrumental of a famous song i had kept repeating on my sisters disc man from Nairobi to Kitale, the song grew in me i think i memorised all the lyrics R-Kelly was saying it was his song haha. As time and years when by i learned about Virtual Dj and its intricasies and started making my own mixes. Some of them having rookie mistakes and BPM mismatches. am sure youl get to here how i sucked long time ago haha.I become better and good at it. While all this was going i was going to school and also living another life in the society. I did Computer science in University, I took an interest in programming leading me here. Because i have been making this music mixes and storing them i tought why not make an appliication which would show case my skills in this fields. Programming being the main priority here i decided to make the application as cool and as intuitive as i can make it be. I have conflicting goals that guided me to making this application. I hope by the end of it all both myself and the intended users of this application will be impressed if not slightly satisfied. One of this goals was to market and show case my skill in the programming realm. the other core goal was to give my fans a very cool sophisticated and satisfying applicatino that will at the very list get bit of there attention. I hope to atleast achieve one hehe.
                    Enough said no to the flesh of this text. In this frontend application i used Javascript framework (React JS). I have no particular reason for choosing this one, i generally have a liking to javascript being a language that manipulates DOM elements smoothly and also being a great use case of a single page application. Since most of the intereation in the application is going to be user center togethere with there data then i tought an SPA would be a greate solution to this. In side this React framework i have use atlease all the core features and implementatino of Javascript language having being modified in the React Realm.I have use the following hooks; Reducer, Context, States. Canvas element to have an audio visualizer similar to those bars and waves that you would see in a music player but this on in my application is the analysis of the audio nodes as they are playing. This data is extrapolated and drawn on a canvas element and clear every time to give the cool animation.Multilingual support, this was especially since music is not country based but international comodity then i thought i shouldnt be biased but have multiple language support on the application so that other users from other parts of the world could sign in and enjoy as well. Among the features or the implementations that i have added in the frontend include a dark mode selection. Chart js which helps me visualize how the users are interating with my content. on the backend side i have also implenented an API to google console which i get data on how the application is doing as SEO is concerned. Not that i want to rank or anything but since its a tool with data that be great to use also when i get an employer with such needs i can easily adapt. There is also use of FETCH API that gets data on NASA's astronomy picture of the day together with its descriotion and displays them. I am a fun of photography and nature as general, so i thoought is a good place to get this images and show to the fans and users, they are cool images either way. I will be talking about the backend side of this application when am finished with it. I use and am fan of regular expressions, this is my go to for form validation. i recently found and appreciated how they have been used all over in our development environments. SO i have implemented its uses in all all input fields in this application. I have also used cookies to store last song and time played, the mode that was set but use which does not require database storage.
                </Tab>
                <Tab eventKey="support" title="Support and Good Course">
                    HeHe now that you are here. I am quite sure there many good souls who like to see others do better or good. if your that kind or person why not extend that curtesy and donate to my patreon. i have a plee written and described there. otherwise i enjoy and love what i do i wont stop neither loose motivation. but i just though why not put it there. Fun fact in all of my mixes you will not hear my nome dropped anywhere
                </Tab>
            </Tabs>
        </div>
    )
}
