//Music player default state type
export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
export const SET_TOGGLE_RANDOM = 'SET_TOGGLE_RANDOM';
export const SET_TOGGLE_REPEAT = 'SET_TOGGLE_REPEAT';
export const SET_TOGGLE_PLAYING = 'SET_TOGGLE_PLAYING';
export const SET_ACTIVE_PLAYLIST_ARRAY = 'SET_ACTIVE_PLAYLIST_ARRAY';
export const SET_RECENT_SEEK_TIME = 'SET_RECENT_SEEK_TIME';
export const SET_FAVOURITE_MIX_ITEM = 'SET_FAVOURITE_MIX_ITEM';
export const SET_VOLUME = 'SET_VOLUME';
export const SET_MIX_ITEM_DURATION = 'SET_MIX_ITEM_DURATION';
export const SET_ABLE_TO_PLAY_OR_LOADING = 'SET_ABLE_TO_PLAY_OR_LOADING';
export const SET_COMPLETE_PLAYLIST = 'SET_COMPLETE_PLAYLIST';
export const SET_ALLMUSICMIXES = 'SET_ALLMUSICMIXES';
export const SET_MUSIC_PLAYING_STATUS = 'SET_MUSIC_PLAYING_STATUS';

export const SET_MIX_ITEM_LOADING_SPINNER = 'SET_MIX_ITEM_LOADING_SPINNER';
