//Main Application theme state type
export const SET_MAIN_APP_DARKMODE = 'SET_MAIN_APP_DARKMODE';
export const SET_MUSIC_APP_DARKMODE = 'SET_MUSIC_APP_DARKMODE';
export const SET_SPECTRUM_TYPE = 'SET_SPECTRUM_TYPE';
export const SET_MIX_ITEM_LOADING_SPINNER = 'SET_MIX_ITEM_LOADING_SPINNER';

//Admin Action state type
export const SET_ENABLE_GLOBAL_AUDIO_VISUALIZER = 'SET_ENABLE_GLOBAL_AUDIO_VISUALIZER';
export const SET_ENABLE_GLOBAL_ASTRONOMY_PICTURE = 'SET_ENABLE_GLOBAL_ASTRONOMY_PICTURE';
export const SET_ENABLE_GLOBAL_SHAZAM_SEARCH = 'SET_ENABLE_GLOBAL_SHAZAM_SEARCH';
export const SET_ENABLE_GLOBAL_DOWNLOAD_OPTION = 'SET_ENABLE_GLOBAL_DOWNLOAD_OPTION';
export const SET_ENABLE_GLOBAL_CALM_ANXIETY = 'SET_ENABLE_GLOBAL_CALM_ANXIETY';
export const SET_ENABLE_GLOBAL_ALLOW_USERS_SEE_OTHERS_ONLINE_ACTIVITY = 'SET_ENABLE_GLOBAL_ALLOW_USERS_SEE_OTHERS_ONLINE_ACTIVITY';
export const SET_NOTIFIATION_TEXT_ITEM = 'SET_NOTIFIATION_TEXT_ITEM';

//Application stats states
export const SET_CUMMULATIVE_MINUTES_LISTENED = 'SET_CUMMULATIVE_MINUTES_LISTENED';
export const SET_COMMULATIVE_PLAYS_COUNT = 'SET_COMMULATIVE_PLAYS_COUNT';
export const SET_CUMMULATIVE_COMMENTS = 'SET_CUMMULATIVE_COMMENTS';
export const SET_TOTAL_USERS_COUNT = 'SET_TOTAL_USERS_COUNT';
export const SET_TOTAL_SHAZAM_COUNT = 'SET_TOTAL_SHAZAM_COUNT';
export const SET_HIGEST_FAVOURITES = 'SET_HIGEST_FAVOURITES';
export const SET_CUMMULATIVE_DOWNLOADS = 'SET_CUMMULATIVE_DOWNLOADS';
export const SET_CUMMULATIVE_QUIZ_ATTEMPTS = 'SET_CUMMULATIVE_QUIZ_ATTEMPTS';
export const SET_THANOS_SNAP_ANIMATION = 'SET_THANOS_SNAP_ANIMATION';

//User Profile state
export const SET_USER_FIRSTNAME = 'SET_USER_FIRSTNAME'
export const SET_USER_LASTNAME  = 'SET_USER_LASTNAME'
export const SET_USER_USERNAME = 'SET_USER_USERNAME';
export const SET_USER_EXCERPT = 'SET_USER_EXCERPT'
export const SET_USER_EMAIL = 'SET_USER_EMAIL'
export const SET_USER_NUMBER = 'SET_USER_NUMBER'
export const SET_USER_USERIMAGE = 'SET_USER_USERIMAGE'
export const SET_USER_ACTIVEPLAYLIST = 'SET_USER_ACTIVEPLAYLIST'
export const SET_USER_LASTSONG = 'SET_USER_LASTSONG'
export const SET_USER_LAST_SEEKTIME = 'SET_USER_LAST_SEEKTIME'
export const SET_USER_TOTALMINUTESLISTENED = 'SET_USER_TOTALMINUTESLISTENED'
export const SET_USER_TOTAL_PLAYS_COUNT = 'SET_USER_TOTAL_PLAYS_COUNT'
export const SET_USER_ROLE = 'SET_USER_ROLE'
export const SET_USER_TOTAL_QUIZE_POINTS = 'SET_USER_TOTAL_QUIZE_POINTS'
export const SET_USER_LAST_QUIZ_DATE = 'SET_USER_LAST_QUIZ_DATE'
export const SET_USER_FAVOURITE_LIST_ADD = 'SET_USER_FAVOURITE_LIST_ADD';
export const SET_USER_FAVOURITE_LIST_REMOVE = 'SET_USER_FAVOURITE_LIST_REMOVE';
export const SET_USER_SHAZAM_LIST = 'SET_USER_SHAZAM_LIST';
export const SET_USER_HISTORY_LIST = 'SET_USER_HISTORY_LIST';
export const SET_USER_FAVOURITES_COUNT = 'SET_USER_FAVOURITES_COUNT';
export const SET_USER_IDENTIFIED_SONGS_COUNT = 'SET_USER_IDENTIFIED_SONGS_COUNT';
export const SET_USER_COMMENTS = 'SET_USER_COMMENTS';
export const SET_USER_COMMENTS_COUNT = 'SET_USER_COMMENTS_COUNT';
export const SET_USER_FIREBASE_UUID = 'SET_USER_FIREBASE_UUID';

//User state type
export const SET_SHOW_MY_ONLINE_STATUS = 'SET_SHOW_MY_ONLINE_STATUS';
export const SET_SHOW_OTHERS_COMMENTS = 'SET_SHOW_OTHERS_COMMENTS';
export const SET_ALLOW_RANDOM_QUIZ = 'SET_ALLOW_RANDOM_QUIZ';
export const SET_ARTIFICIAL_WEATHER = 'SET_ARTIFICIAL_WEATHER';
export const SET_ONLINE_USERS_LIST = 'SET_ONLINE_USERS_LIST';

//other global state type
export const SET_ASTRONOMY_PICTURE = 'SET_ASTRONOMY_PICTURE';
export const SET_GLOBAL_LANGUAGE = 'SET_GLOBAL_LANGUAGE';

//Intro JS allow the aside navigation to be drawn when its mobile device
export const SET_ASIDE_NAVIGATION_OPEN_APP_TOUR = 'SET_ASIDE_NAVIGATION_OPEN_APP_TOUR';
export const SET_ENABLE_APPLICATION_TOUR = 'SET_ENABLE_APPLICATION_TOUR'